package com.st.service;


import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import com.st.dao.TrainingRepository;
import com.st.entity.TrainingCenter;

@Component
public class TrainingService {
	@Autowired
	TrainingRepository repository;
	// create Training Center
	 public TrainingCenter saveTraining(TrainingCenter trainingCenter ) {	
		 long seconds = System.currentTimeMillis() / 1000; //Epoch time generated by System, not by user
		 trainingCenter.setCreatedOn(seconds);
		 TrainingCenter trainingCenter1 = repository.save(trainingCenter);
		 return trainingCenter1;		 
	 }
	 //List of Training Center
	 public List<TrainingCenter> getAllTrainingCenters() {
	        return repository.findAll();
	    }

}
